### ISSUE TITLE
Problem with Installation from pypi

### ISSUE THREAD

**Issue by hushaohan** [tpircher/quine-mccluskey#6]
Installation from source using something like `pip install -e .` seems to work. but installation from pypi wouldn't proceed correctly:

```
$ pip install quine_mccluskey
Collecting quine_mccluskey
  Using cached https://files.pythonhosted.org/packages/28/b1/d41dbf8a109c6d4c61966a27a18118cce9ff5fffd9a2d558c6b0d67a5f55/quine_mccluskey-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wh/9f9nhgcj4g5_18lv3xt7z9j40000gn/T/pip-install-x_v769mk/quine-mccluskey/setup.py", line 18, in <module>
        long_description=open('README.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wh/9f9nhgcj4g5_18lv3xt7z9j40000gn/T/pip-install-x_v769mk/quine-mccluskey/
```

Tested on mac using a fresh python 3.7.2 virtualenv.

**Comment by tpircher-zz** [comment]
This should be fixed now in v0.3
